version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: postgres           
      POSTGRES_PASSWORD: 12345          
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pokemon_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      
      DATABASE_URL: postgresql://postgres:12345@postgres:5432/pokemon_db
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/app
    command: >
      sh -c "sleep 5 && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data: